FROM python:3.7.0

ARG KUBECTL_VERSION=v1.16.6
ENV WORKSPACE /src/preprocessing-service
WORKDIR $WORKSPACE
ENV PYTHONPATH /src/preprocessing-service
ARG RKE_VERSION=v1.0.2
ARG CLI_VERSION=v2.3.2
ARG RANCHER_HELM_VERSION=v3.6.0
ARG SONOBUOY_VERSION=0.18.2
ARG TERRAFORM_VERSION=0.12.10

COPY [".", "$WORKSPACE"]

RUN cd $WORKSPACE && \
    pip install --upgrade pip && \
    pip install -r requirements-sono.txt

ENTRYPOINT ["./run_sono.sh"]