FROM python:3.7.0

ENV WORKSPACE /src/
WORKDIR $WORKSPACE
ENV PYTHONPATH /src/preprocessing-service
ARG SONOBUOY_VERSION=0.18.2

COPY [".", "$WORKSPACE"]

RUN cd $WORKSPACE && \
    pip install --upgrade pip && \
    pip install -r requirements-sono.txt && \
    chmod +x run_sono.sh

ENTRYPOINT ["./run_sono.sh"]